name: Zackary Scholl
description:  Research in protein folding and biophysics

sass:
  sass_dir: assets/css/_sass
  style: :compressed

#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

#url: http://localhost:4000
#relative_permalinks: true
#permalink: /:year/:month/:title/
permalink: /:title/
owner:
    name: zns18
    twitter: zack_118
    github: zns18
    disqus_shortname: #

ga_id: UA-2345677-4
ga_username: auto

timezone: Africa/Accra
